apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: y0dazaq7q-nodejs 
  janus-idp.io/tekton: y0dazaq7q-nodejs
  backstage.io/kubernetes-id: y0dazaq7q-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y0dazaq7q-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml