apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: y0dazaq7q-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: y0dazaq7q-nodejs 
  name: y0dazaq7q-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: y0dazaq7q-nodejs 
